language: ruby
dist: trusty
rvm:
  - 2.5.3
before_install:
  - yes | gem update --system --force
  - gem install bundler
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - bundle exec rspec spec
cache: bundler
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
